config/routes.rb
Rails.application.routes.draw do
  resources :skus, only: [:index]
  resources :suppliers, only: [:index]
  resources :csv_files, only: [:index, :create]
  root to: 'csv_files#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csv_file.rb
class CsvFile < ApplicationRecord
  SUPPLIER_FILE = 'suppliers.csv'
  SKU_FILE = 'sku.csv'

  has_attached_file :attachment, attachment_presence: true
  validates_attachment :attachment,
    content_type: { content_type: 'text/plain' },
    file_name: { matches: [/#{SUPPLIER_FILE}/, /#{SKU_FILE}/] }

  enum status: { active: 0, processed: 1 }

  scope :active, -> { where(status: 0) }
end

app/models/sku.rb
class Sku < ApplicationRecord
  belongs_to :supplier, primary_key: 'code', foreign_key:'supplier_code'

  validates :sku, :supplier_code, :name, :price, presence: true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :skus, primary_key: 'code', foreign_key:'supplier_code'

  validates :name, :code, presence: true
  validates :code, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  def index
    @csv_file = CsvFile.new
  end

  def create
    @csv_file = CsvFile.new(csv_file_params)

    respond_to do |format|
      if @csv_file.save
        flash[:notice] = 'Csv file was successfully created.'
        format.html { redirect_to action: :index }
      else
        format.html { render :index }
      end
    end
  end

  private
    def csv_file_params
      params.fetch(:csv_file, {}).permit(:attachment)
    end
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  def index
    # Add paginatio when will be requirements
    @skus = Sku.includes(:supplier).limit(100)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    # Add paginatio when will be requirements
    @suppliers = Supplier.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/helpers/skus_helper.rb
module SkusHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/csv_files/_form.html.erb
<%= form_with(model: csv_file, local: true) do |form| %>
  <% if csv_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_file.errors.count, "error") %> prohibited this csv_file from being saved:</h2>

      <ul>
      <% csv_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.file_field :attachment, :class => 'btn btn-outline-info btn-sm' %>
  <br>
  <br>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'btn btn-info btn-sm' %>
  </div>
<% end %>

app/views/csv_files/index.html.erb
<h1>Upload Csv File</h1>
<br>
<br>

<%= render 'form', csv_file: @csv_file %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Supplier', suppliers_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'SKU', skus_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Csv Parser" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Csv Parser" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: 'layouts/navigation' %>
    <main role="main" class='text-center'>
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/skus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skus</h1>

<table class='table'>
  <thead class="thead-dark">
    <tr>
      <th>Sku</th>
      <th>Supplier Name</th>
      <th>Name</th>
      <th>Additional1</th>
      <th>Additional2</th>
      <th>Additional3</th>
      <th>Additional4</th>
      <th>Additional5</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @skus.each do |sku| %>
      <%= cache sku do %>
        <tr>
          <td><%= sku.sku %></td>
          <td><%= sku.supplier.name %></td>
          <td><%= sku.name %></td>
          <td><%= sku.additional1 %></td>
          <td><%= sku.additional2 %></td>
          <td><%= sku.additional3 %></td>
          <td><%= sku.additional4 %></td>
          <td><%= sku.additional5 %></td>
          <td><%= sku.price %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suppliers</h1>

<table class='table'>
  <thead class="thead-dark">
    <tr>
      <th>Code</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <%= cache supplier do %>
        <tr>
          <td><%= supplier.code %></td>
          <td><%= supplier.name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>